version: "2.2"

services:
      # docker container exec -it test_postgres bash -c 'PGPASSWORD=password psql -U mamad -h 20.0.0.10 mamad'
      postgres:
            image: postgres:14.1
            container_name: test_postgres
            restart: always
            expose:
                  - 5432
            environment:
                  - POSTGRES_USER=mamad
                  - POSTGRES_PASSWORD=password
                  - POSTGRES_DB=mamad
            networks:
                  service_dependency_net:
                        ipv4_address: 20.0.0.10
            volumes:
                  - ~/databases/test_postgres:/var/lib/postgresql/data
networks:
      service_dependency_net:
            driver: bridge
            name: test_service_dependency_net
            ipam:
                  config:
                        - subnet: 20.0.0.0/24
